### PR TITLE
getAllowedToken task

### PR DESCRIPTION
**Pull request by ironFe93**
## What

- recreates the allowedTokens script in ethers/hardhat
- fix: missing customSmartWalletRelayVerifier contract on all scripts

## Why

- ethers migration

## Refs

- (optional: include links to other issues, PRs, tickets, etc)

### CODE REVIEW

**Comment by franciscotobar** [comment]
I just test it and it works properly but Im getting the same warnings from the lint_test from typescript.

**Comment by ironFe93** [comment]
Yeah, probably has something to do with dependencies. I did not touch any of the files where the errors appear.

**Comment by antomor** [comment]
@ironFe93 I've rebased the branch, but when I try to deploy the contracts I've the following error: 
```
An unexpected error occurred:

SocketError: closed
    at Socket.onSocketClose (...)
```
I've also checked the same on the [backup branch](https://github.com/rsksmart/rif-relay-contracts/tree/feature/PP-278/PP-329/getAllowedTokens-backup) and the error is the same. Could you please check it?

**Comment by franciscotobar** [comment]
I tried it and its working properly. Im just getting some warnings about typing, maybe we could discuss it since I did some updates.

**Comment by ironFe93** [comment]
@antomor might be something related to your rskj node. Are you on IRIS?

**Comment by antomor** [comment]
> @antomor might be something related to your rskj node. Are you on IRIS? Please take a look at this discussion https://ethereum.stackexchange.com/questions/130028/hardhat-deploy-script-on-rsk-throws-und-err-socket

@ironFe93 You're right. I tested with 3.3 and 4.x, and I confirm that it works with HOP (4.x) only. If we still have this issue, we should probably document it in the readme.

**Review by antomor — APPROVED** [review]
LGTM

**Pull request merged**
